/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.damayo.basiccrud;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class addEmployee extends javax.swing.JInternalFrame {

    /**
     * Creates new form addEmployee
     */
    public addEmployee() {
        initComponents();
    }
    
    private void insertDataIntoDatabase() {
        Connection connection = null;
        PreparedStatement preparedStatement = null;

        try {
            String query = "INSERT INTO `employee`(`id`, `fname`, `mnane`, `lname`, `username`, `password`, `usertype`, \n" +
"                       `gender`, `contact`, `address`, `status`)\n" +
"                       VALUES (?,?,?,?,?,?,?,?,?,?,?)";
            connection = DatabaseUtil.getConnection();
            
            if(fName.getText().isEmpty() ||lName.getText().isEmpty()
                        ||userName.getText().isEmpty() ||passField.getText().isEmpty()
                        ||cntctField.getText().isEmpty()||addressField.getText().isEmpty()){
                    JOptionPane.showMessageDialog(this, "Please fillout important fields.");
            }else{
                preparedStatement = connection.prepareStatement(query);
                preparedStatement.setString(1, null);
                preparedStatement.setString(2, fName.getText());
                preparedStatement.setString(3, mName.getText());
                preparedStatement.setString(4, lName.getText());
                preparedStatement.setString(5, userName.getText());
                preparedStatement.setString(6, passField.getText());
                preparedStatement.setString(7, type.getSelectedItem().toString());
                preparedStatement.setString(8, gender.getSelectedItem().toString());
                preparedStatement.setString(9, cntctField.getText());
                preparedStatement.setString(10, addressField.getText());
                preparedStatement.setString(11, "1");
            }
            int rowsAffected = preparedStatement.executeUpdate();

            if (rowsAffected > 0) {
                // Data inserted successfully
                JOptionPane.showMessageDialog(this, "Data inserted successfully");
                
                // Clear text fields after successful insertion if needed
                fName.setText("");
                mName.setText("");
                lName.setText("");
                userName.setText("");
                passField.setText("");
                type.setSelectedItem("Employee");
                gender.setSelectedItem("Male");
                cntctField.setText("");
                addressField.setText("");
                
            } else {
                // No rows affected, insertion failed
                JOptionPane.showMessageDialog(this, "Failed to insert data");
            }
        } catch (SQLException e) {
            e.printStackTrace();
        } finally {
            // Close resources in the reverse order of their creation
            try {
                if (preparedStatement != null) {
                    preparedStatement.close();
                }
                if (connection != null) {
                    connection.close();
                }
            } catch (SQLException e) {
                e.printStackTrace();
            }
        }
    }
    
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jProgressBar1 = new javax.swing.JProgressBar();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        gender = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        fName = new javax.swing.JTextField();
        mName = new javax.swing.JTextField();
        lName = new javax.swing.JTextField();
        addressField = new javax.swing.JTextField();
        passWord = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        addBtn = new javax.swing.JButton();
        clearBtn = new javax.swing.JButton();
        passField = new javax.swing.JTextField();
        userName = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        cntctField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        type = new javax.swing.JComboBox<>();

        setClosable(true);
        setIconifiable(true);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(749, 527));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ADD EMPLOYEE");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 10, 200, 27);

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("First Name :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 80, 70, 20);

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Middle Name :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(10, 150, 90, 16);

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Last Name :");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(20, 220, 80, 16);

        gender.setBackground(new java.awt.Color(0, 153, 255));
        gender.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        gender.setForeground(new java.awt.Color(255, 255, 255));
        gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        jPanel1.add(gender);
        gender.setBounds(460, 280, 130, 40);

        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Gender :");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(390, 290, 60, 16);

        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Address :");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(30, 360, 60, 16);

        fName.setBackground(new java.awt.Color(255, 255, 255));
        fName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        fName.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(fName);
        fName.setBounds(100, 70, 230, 40);

        mName.setBackground(new java.awt.Color(255, 255, 255));
        mName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mName.setForeground(new java.awt.Color(0, 0, 0));
        mName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                mNameKeyTyped(evt);
            }
        });
        jPanel1.add(mName);
        mName.setBounds(100, 140, 230, 40);

        lName.setBackground(new java.awt.Color(255, 255, 255));
        lName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lName.setForeground(new java.awt.Color(0, 0, 0));
        lName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                lNameKeyTyped(evt);
            }
        });
        jPanel1.add(lName);
        lName.setBounds(100, 210, 230, 40);

        addressField.setBackground(new java.awt.Color(255, 255, 255));
        addressField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        addressField.setForeground(new java.awt.Color(0, 0, 0));
        addressField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addressFieldMouseClicked(evt);
            }
        });
        addressField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressFieldActionPerformed(evt);
            }
        });
        jPanel1.add(addressField);
        addressField.setBounds(100, 350, 590, 40);

        passWord.setForeground(new java.awt.Color(0, 0, 0));
        passWord.setText("Password :");
        jPanel1.add(passWord);
        passWord.setBounds(380, 150, 70, 16);

        jLabel18.setForeground(new java.awt.Color(0, 0, 0));
        jLabel18.setText("User Type :");
        jPanel1.add(jLabel18);
        jLabel18.setBounds(380, 220, 70, 16);

        addBtn.setBackground(new java.awt.Color(0, 204, 102));
        addBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        addBtn.setForeground(new java.awt.Color(255, 255, 255));
        addBtn.setText("ADD EMPLOYEE");
        addBtn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });
        jPanel1.add(addBtn);
        addBtn.setBounds(210, 420, 154, 40);

        clearBtn.setBackground(new java.awt.Color(204, 102, 0));
        clearBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        clearBtn.setForeground(new java.awt.Color(255, 255, 255));
        clearBtn.setText("CLEAR");
        clearBtn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        clearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtnActionPerformed(evt);
            }
        });
        jPanel1.add(clearBtn);
        clearBtn.setBounds(420, 420, 154, 40);

        passField.setBackground(new java.awt.Color(255, 255, 255));
        passField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        passField.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(passField);
        passField.setBounds(460, 140, 230, 40);

        userName.setBackground(new java.awt.Color(255, 255, 255));
        userName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        userName.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(userName);
        userName.setBounds(460, 70, 230, 40);

        jLabel21.setForeground(new java.awt.Color(0, 0, 0));
        jLabel21.setText("Username :");
        jPanel1.add(jLabel21);
        jLabel21.setBounds(378, 80, 70, 16);

        cntctField.setBackground(new java.awt.Color(255, 255, 255));
        cntctField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cntctField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cntctFieldActionPerformed(evt);
            }
        });
        cntctField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cntctFieldKeyTyped(evt);
            }
        });
        jPanel1.add(cntctField);
        cntctField.setBounds(100, 280, 230, 40);

        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Contact # :");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(20, 290, 70, 16);

        type.setBackground(new java.awt.Color(0, 153, 255));
        type.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        type.setForeground(new java.awt.Color(255, 255, 255));
        type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Employee", "Admin" }));
        type.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeActionPerformed(evt);
            }
        });
        jPanel1.add(type);
        type.setBounds(460, 210, 130, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 761, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 489, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
    insertDataIntoDatabase();
    }//GEN-LAST:event_addBtnActionPerformed

    private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnActionPerformed
                fName.setText("");
                mName.setText("");
                lName.setText("");
                userName.setText("");
                passField.setText("");
                type.setSelectedItem("Employee");
                gender.setSelectedItem("Male");
                cntctField.setText("");
                addressField.setText("");
    }//GEN-LAST:event_clearBtnActionPerformed

    private void addressFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressFieldActionPerformed
       
    }//GEN-LAST:event_addressFieldActionPerformed

    private void addressFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addressFieldMouseClicked
      
    }//GEN-LAST:event_addressFieldMouseClicked

    private void cntctFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cntctFieldKeyTyped
        
    }//GEN-LAST:event_cntctFieldKeyTyped

    private void mNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mNameKeyTyped

    }//GEN-LAST:event_mNameKeyTyped

    private void lNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lNameKeyTyped

    }//GEN-LAST:event_lNameKeyTyped

    private void cntctFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cntctFieldActionPerformed
 
    }//GEN-LAST:event_cntctFieldActionPerformed

    private void typeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_typeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JTextField addressField;
    private javax.swing.JButton clearBtn;
    private javax.swing.JTextField cntctField;
    private javax.swing.JTextField fName;
    private javax.swing.JComboBox<String> gender;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JTextField lName;
    private javax.swing.JTextField mName;
    private javax.swing.JTextField passField;
    private javax.swing.JLabel passWord;
    private javax.swing.JComboBox<String> type;
    private javax.swing.JTextField userName;
    // End of variables declaration//GEN-END:variables
}
