/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.damayo.basiccrud;

import java.util.*;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import javax.swing.*;

public class recordFrame extends javax.swing.JInternalFrame {

    /**
     * Creates new form search
     */
    public recordFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        inputBtn = new javax.swing.JButton();
        availableBtn = new javax.swing.JButton();
        assignedBtn = new javax.swing.JButton();
        outputBtn = new javax.swing.JButton();
        assEmpBtn = new javax.swing.JButton();
        textFieldArea = new javax.swing.JLabel();
        note = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("VIEW REPORTS");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 220, 44));

        inputBtn.setBackground(new java.awt.Color(0, 153, 255));
        inputBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        inputBtn.setForeground(new java.awt.Color(255, 255, 255));
        inputBtn.setText("INPUT DEVICES");
        inputBtn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        inputBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        inputBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputBtnActionPerformed(evt);
            }
        });
        jPanel1.add(inputBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 260, 50));

        availableBtn.setBackground(new java.awt.Color(0, 153, 255));
        availableBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        availableBtn.setForeground(new java.awt.Color(255, 255, 255));
        availableBtn.setText("AVAILBALE PERIPHERALS");
        availableBtn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        availableBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        availableBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                availableBtnActionPerformed(evt);
            }
        });
        jPanel1.add(availableBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 260, 50));

        assignedBtn.setBackground(new java.awt.Color(0, 153, 255));
        assignedBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        assignedBtn.setForeground(new java.awt.Color(255, 255, 255));
        assignedBtn.setText("ASSIGNED PERIPHERALS");
        assignedBtn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        assignedBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        assignedBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignedBtnActionPerformed(evt);
            }
        });
        jPanel1.add(assignedBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 260, 50));

        outputBtn.setBackground(new java.awt.Color(0, 153, 255));
        outputBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        outputBtn.setForeground(new java.awt.Color(255, 255, 255));
        outputBtn.setText("OUTPUT DEVICES");
        outputBtn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        outputBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outputBtnActionPerformed(evt);
            }
        });
        jPanel1.add(outputBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, 260, 50));

        assEmpBtn.setBackground(new java.awt.Color(0, 153, 255));
        assEmpBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        assEmpBtn.setForeground(new java.awt.Color(255, 255, 255));
        assEmpBtn.setText("ASSIGNED EMPLOYEE ");
        assEmpBtn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        assEmpBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assEmpBtnActionPerformed(evt);
            }
        });
        jPanel1.add(assEmpBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 390, 260, 50));

        textFieldArea.setFont(new java.awt.Font("Segoe UI", 1, 200)); // NOI18N
        textFieldArea.setForeground(new java.awt.Color(51, 51, 51));
        jPanel1.add(textFieldArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 120, 350, 200));

        note.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        note.setForeground(new java.awt.Color(0, 0, 102));
        jPanel1.add(note, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 300, 390, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 793, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputBtnActionPerformed
        textFieldArea.setText("");
        try {
            String query = "SELECT * FROM peripheral WHERE type LIKE 'Input' AND (status = 1 OR status = 2)";
            ResultSet resultSet = DatabaseUtil.executeQuery(query);
            int count = 0;
            while (resultSet.next()) {
                count++;
            }
            textFieldArea.setText(count+"");
            note.setText("There are "+count+" INPUT Devices.");
        } catch (SQLException ex) {
            Logger.getLogger(manageEmpFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_inputBtnActionPerformed

    private void availableBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_availableBtnActionPerformed
        textFieldArea.setText("");
        try {
            String query = "SELECT * FROM peripheral WHERE status = 1";
            ResultSet resultSet = DatabaseUtil.executeQuery(query);
            int count = 0;
            while (resultSet.next()) {
                count++;
            }
            textFieldArea.setText(count+"");
            note.setText("There are "+count+" Available PERIPHERALS.");
        } catch (SQLException ex) {
            Logger.getLogger(manageEmpFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_availableBtnActionPerformed

    private void assignedBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignedBtnActionPerformed
        textFieldArea.setText("");
        try {
            String query = "SELECT * FROM peripheral WHERE status = 2";
            ResultSet resultSet = DatabaseUtil.executeQuery(query);
            int count = 0;
            while (resultSet.next()) {
                count++;
            }
            textFieldArea.setText(count+"");
            note.setText("There are "+count+" Assigned PERIPHERALS.");
        } catch (SQLException ex) {
            Logger.getLogger(manageEmpFrame.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_assignedBtnActionPerformed

    private void outputBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outputBtnActionPerformed
       textFieldArea.setText("");
        try {
            String query = "SELECT * FROM peripheral WHERE type LIKE 'Output' AND (status = 1 OR status = 2)";
            ResultSet resultSet = DatabaseUtil.executeQuery(query);
            int count = 0;
            while (resultSet.next()) {
                count++;
            }
            textFieldArea.setText(count+"");
            note.setText("There are "+count+" OUTPUT Devices.");
        } catch (SQLException ex) {
            Logger.getLogger(manageEmpFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_outputBtnActionPerformed

    private void assEmpBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assEmpBtnActionPerformed
        textFieldArea.setText("");
        try {
            String query = "SELECT * FROM assignment WHERE status = 1";
            ResultSet resultSet = DatabaseUtil.executeQuery(query);
            int count = 0;
            while (resultSet.next()) {
                count++;
            }
            textFieldArea.setText(count+"");
            note.setText("There are "+count+" EPLOYEES assigned w/ peripheral.");
        } catch (SQLException ex) {
            Logger.getLogger(manageEmpFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_assEmpBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton assEmpBtn;
    private javax.swing.JButton assignedBtn;
    private javax.swing.JButton availableBtn;
    private javax.swing.JButton inputBtn;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel note;
    private javax.swing.JButton outputBtn;
    private javax.swing.JLabel textFieldArea;
    // End of variables declaration//GEN-END:variables
}
